# Generated by Django 4.2.1 on 2023-06-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=False, upload_to='posts/'),
        ),
    ]
