# Generated by Django 4.2.1 on 2023-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='posts/'),
        ),
    ]
